is_border_leaf: true
lacp_pcs:
  - 10
  - 11
  - 12
  - 13
mclag_member_pcs:
  - lag: PortChannel10
  - lag: PortChannel11
  - lag: PortChannel12
  - lag: PortChannel13
sonic_bgp:
  - bestpath:
      as_path:
        multipath_relax: true
    bgp_as: '{{ bgp_asn }}'
    router_id: '{{ bgp_router_id }}'
  - bgp_as: '{{bgp_asn}}'
    vrf_name: Vrf1
  - bgp_as: '{{ bgp_asn }}'
sonic_bgp_af:
  - address_family:
      afis:
        - afi: ipv4
          max_path:
            ebgp: 2
          redistribute:
            - protocol: connected
          safi: unicast
        - advertise_all_vni: true
          afi: l2vpn
          safi: evpn
    bgp_as: '{{bgp_asn}}'
  - address_family:
      afis:
        - advertise_prefix:
            - afi: ipv4
              safi: unicast
          afi: l2vpn
          safi: evpn
        - afi: ipv4
          redistribute:
            - protocol: connected
          safi: unicast
    bgp_as: '{{ bgp_asn }}'
    vrf_name: Vrf1
sonic_bgp_neighbors:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: Eth1/56
        peer_group: spine-leaf
      - neighbor: Eth1/55
        peer_group: spine-leaf
    peer_group:
      - '{{sonic_bgp_spineleaf_peergroup}}'
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 20.0.2.2
        remote_as:
          peer_as: 64626
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - neighbor: 20.0.3.2
        remote_as:
          peer_as: 64626
    vrf_name: Vrf1
sonic_bgp_neighbors_af:
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/56
      - address_family: '{{sonic_bgp_fabriclink_neighbors_aflist}}'
        neighbor: Eth1/55
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 20.0.2.2
    vrf_name: Vrf1
  - bgp_as: '{{bgp_asn}}'
    neighbors:
      - address_family:
          - activate: true
            afi: ipv4
            safi: unicast
        neighbor: 20.0.3.2
    vrf_name: Vrf1
sonic_config:
  lines: []
sonic_interfaces:
  - description: '"Uplink"'
    enabled: true
    name: Eth1/1
  - description: '"Uplink"'
    enabled: true
    name: Eth1/2
  - description: '"Node-01_eth1-NDC1-25G-2"'
    enabled: true
    name: Eth1/5
  - description: '"Node-02_eth1-NDC1-25G-2"'
    enabled: true
    name: Eth1/6
  - description: '"Node-03_eth1-NDC1-25G-2"'
    enabled: true
    name: Eth1/7
  - description: '"Node-04_eth1-NDC1-25G-2"'
    enabled: true
    name: Eth1/8
  - description: '"MCLAG to NewFabric-LEAF-1 Eth1/47"'
    enabled: true
    name: Eth1/47
  - description: '"MCLAG to NewFabric-LEAF-1 Eth1/48"'
    enabled: true
    name: Eth1/48
  - description: '"Uplink to NewFabric-SPINE-2 Eth1/2"'
    enabled: true
    name: Eth1/55
  - description: '"Uplink to NewFabric-SPINE-1 Eth1/2"'
    enabled: true
    name: Eth1/56
  - description: router-id
    name: '{{ loopback_inf0 }}'
  - description: vtep
    name: '{{ loopback_inf1 }}'
  - description: '"LAG to Compute_1_Node-01_bond0"'
    mtu: 9216
    name: PortChannel10
  - description: '"LAG to Compute_1_Node-02_bond0"'
    mtu: 9216
    name: PortChannel11
  - description: '"LAG to Compute_1_Node-03_bond0"'
    mtu: 9216
    name: PortChannel12
  - description: '"LAG to Compute_1_Node-04_bond0"'
    mtu: 9216
    name: PortChannel13
sonic_l2_interfaces:
  - name: Eth1/1
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: Eth1/2
    trunk:
      allowed_vlans:
        - vlan: 200
  - name: PortChannel 10
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
  - name: PortChannel 11
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
  - name: PortChannel 12
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
  - name: PortChannel 13
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
  - name: PortChannel100
    trunk:
      allowed_vlans:
        - vlan: 101
        - vlan: 102
        - vlan: 60
sonic_l3_interfaces:
  - ipv6:
      enabled: true
    name: Eth1/55
  - ipv6:
      enabled: true
    name: Eth1/56
  - ipv4:
      addresses:
        - address: '{{ loopback0_ip }}'
    name: '{{ loopback_inf0 }}'
  - ipv4:
      addresses:
        - address: '{{ loopback1_ip }}'
    name: '{{ loopback_inf1 }}'
  - ipv4:
      addresses:
        - address: 20.0.2.1/24
    name: Vlan200
sonic_lag_interfaces:
  - members:
      interfaces:
        - member: Eth1/5
    mode: lacp
    name: PortChannel10
  - members:
      interfaces:
        - member: Eth1/6
    mode: lacp
    name: PortChannel11
  - members:
      interfaces:
        - member: Eth1/7
    mode: lacp
    name: PortChannel12
  - members:
      interfaces:
        - member: Eth1/8
    mode: lacp
    name: PortChannel13
  - members:
      interfaces:
        - member: Eth1/47
        - member: Eth1/48
    name: PortChannel100
sonic_system:
  anycast_address:
    ipv4: true
    mac_address: '{{ anycast_mac_address }}'
  hostname: NewFabric-LEAF-2
  interface_naming: standard
sonic_vlans:
  - vlan_id: 200
  - vlan_id: 101
  - vlan_id: 102
  - vlan_id: 60
sonic_vrf_interfaces:
  - members:
      interfaces:
        - name: Vlan101
        - name: Vlan101
        - name: Vlan101
        - name: Vlan60
        - name: Vlan102
        - name: Vlan102
        - name: Vlan102
        - name: Vlan200
    name: Vrf1
sonic_vxlans:
  - evpn_nvo: nvo1
    name: vtep1
    source_ip: '{{ loopback1_ip.split(''/'')[0] }}'
    vlan_map:
      - vlan: 101
        vni: 1010
      - vlan: 102
        vni: 1020
      - vlan: 60
        vni: 600
    vrf_map:
      - vni: 600
        vrf: Vrf1
vlans:
  - 101
  - 102
vrfs:
  - Vrf1
